// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print

var activitiesCmd = &cobra.Command{
	Use:   "activities",
	Short: "Activities commands",
}

func init() {
	cmd.CcCmd.AddCommand(activitiesCmd)

	{ // list-definitions
		var orgid string
		cmd := &cobra.Command{
			Use:   "list-definitions",
			Short: "List Activity Definitions",
			Long:  "List all available activity types with their full schemas, including inputs, outputs, ports, and descriptions. The response is sufficient on its own to construct nodes \u2014 there is no separate schema endpoint.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/v2/activities")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		activitiesCmd.AddCommand(cmd)
	}

	{ // describe
		var orgid string
		var activityName string
		cmd := &cobra.Command{
			Use:   "describe",
			Short: "Describe an Activity",
			Long:  "Retrieve a single activity's full definition, including inputs, outputs, named ports, and the JSON Schema for its inputs \u2014 all returned inline.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/v2/activities/{activityName}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("activityName", activityName)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&activityName, "activity-name", "", "Activity type name (e.g., `play-message`, `queue-contact`).")
		cmd.MarkFlagRequired("activity-name")
		activitiesCmd.AddCommand(cmd)
	}

	{ // get-input-choices
		var orgid string
		var activityName string
		var inputName string
		var mode string
		var query string
		var value string
		var parent_inputs string
		cmd := &cobra.Command{
			Use:   "get-input-choices",
			Short: "Get Activity Input Choices",
			Long:  "Resolve choices for an activity input. Use this when an activity input requires a value from a predefined or dynamically resolved set (e.g., available queues, audio files, agents).\n\nThis endpoint is only valid for inputs that expose choices (an input whose definition includes `allowedValues` or a `choicesEndpoint`, as returned by `describeActivity`). Calling it for an input that does not support choices returns 400.\n\n**Modes:**\n- `list` \u2014 Returns the full set of allowed values for a static-choice input.\n- `search` \u2014 Returns matches for the supplied `query` string. Use for type-ahead UIs over large choice sets.\n- `validate` \u2014 Checks whether a single `value` is allowed and returns its label/metadata if so.\n- `dynamic` \u2014 Resolves cascading choices whose allowed values depend on one or more sibling inputs. Pass the relevant sibling values via `parent_inputs` (e.g., a queue list scoped to a previously selected team).\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/v2/activities/{activityName}/inputs/{inputName}/choices")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("activityName", activityName)
				req.PathParam("inputName", inputName)
				req.QueryParam("mode", mode)
				req.QueryParam("query", query)
				req.QueryParam("value", value)
				req.QueryParam("parent_inputs", parent_inputs)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&activityName, "activity-name", "", "Activity type name.")
		cmd.MarkFlagRequired("activity-name")
		cmd.Flags().StringVar(&inputName, "input-name", "", "Input field name. Must be an input that exposes choices (has `allowedValues` or a `choicesEndpoint`).")
		cmd.MarkFlagRequired("input-name")
		cmd.Flags().StringVar(&mode, "mode", "", "Resolution mode. Defaults to `list`.")
		cmd.Flags().StringVar(&query, "query", "", "Search term. Required when `mode=search`.")
		cmd.Flags().StringVar(&value, "value", "", "Candidate value to validate. Required when `mode=validate`.")
		cmd.Flags().StringVar(&parent_inputs, "parent_inputs", "", "JSON object of parent input values used for cascading resolution. Required when `mode=dynamic`.")
		activitiesCmd.AddCommand(cmd)
	}

	{ // list-definitions-2
		var orgid string
		cmd := &cobra.Command{
			Use:   "list-definitions-2",
			Short: "List Activity Definitions",
			Long:  "List all available activity types with their full schemas, including inputs, outputs, ports, and descriptions. The response is sufficient on its own to construct nodes \u2014 there is no separate schema endpoint.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/v2/activities")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		activitiesCmd.AddCommand(cmd)
	}

	{ // describe-2
		var orgid string
		var activityName string
		cmd := &cobra.Command{
			Use:   "describe-2",
			Short: "Describe an Activity",
			Long:  "Retrieve a single activity's full definition, including inputs, outputs, named ports, and the JSON Schema for its inputs \u2014 all returned inline.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/v2/activities/{activityName}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("activityName", activityName)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&activityName, "activity-name", "", "Activity type name (e.g., `play-message`, `queue-contact`).")
		cmd.MarkFlagRequired("activity-name")
		activitiesCmd.AddCommand(cmd)
	}

	{ // get-input-choices-2
		var orgid string
		var activityName string
		var inputName string
		var search string
		var validate string
		var parentValue string
		var parentInputName string
		cmd := &cobra.Command{
			Use:   "get-input-choices-2",
			Short: "Get Activity Input Choices",
			Long:  "Resolve choices for an activity input. Use this when an activity input requires a value from a predefined or dynamically resolved set (e.g., available queues, audio files, agents).\n\nThis endpoint is only valid for inputs that expose choices (an input whose definition includes `allowedValues` or a `choicesEndpoint`, as returned by `describeActivity`). Calling it for an input that does not support choices returns 400.\n\nPass `search` to filter the choices (type-ahead). Add `validate=true` together with `search` to do a point-lookup of a single value instead of filtering \u2014 the match is against the choice's `value` (its ID), not its display `name`. For a cascading input whose allowed values depend on a sibling input, supply the parent with `parentInputName` and `parentValue`; otherwise a cascading input returns 400.\n\nFiltering and validation apply only to dynamic (`choicesEndpoint`-backed) inputs. A static input always returns its full enumerated list regardless of `search`/`validate`.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/v2/activities/{activityName}/inputs/{inputName}/choices")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("activityName", activityName)
				req.PathParam("inputName", inputName)
				req.QueryParam("search", search)
				req.QueryParam("validate", validate)
				req.QueryParam("parentValue", parentValue)
				req.QueryParam("parentInputName", parentInputName)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&activityName, "activity-name", "", "Activity type name.")
		cmd.MarkFlagRequired("activity-name")
		cmd.Flags().StringVar(&inputName, "input-name", "", "Input field name. Must be an input that exposes choices (has `allowedValues` or a `choicesEndpoint`).")
		cmd.MarkFlagRequired("input-name")
		cmd.Flags().StringVar(&search, "search", "", "Search text used to filter the returned choices (type-ahead). When `validate=true`, this is instead the single value to look up.")
		cmd.Flags().StringVar(&validate, "validate", "", "When `true` and `search` is supplied, performs a point-lookup of the single value in `search` (matched against the choice's `value`/ID) instead of filtering.")
		cmd.Flags().StringVar(&parentValue, "parent-value", "", "Parent input value for a cascading/dynamic input (for example, the selected `channelType`).")
		cmd.Flags().StringVar(&parentInputName, "parent-input-name", "", "Parent input name for a cascading/dynamic input. Required when `parentValue` is provided.")
		activitiesCmd.AddCommand(cmd)
	}

}
