// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print

var campaignGroupCmd = &cobra.Command{
	Use:   "campaign-group",
	Short: "CampaignGroup commands",
}

func init() {
	cmd.CcCmd.AddCommand(campaignGroupCmd)

	{ // list
		var campaignGroupName string
		var page string
		var pageSize string
		var campaignStatus string
		cmd := &cobra.Command{
			Use:   "list",
			Short: "List Campaigns by Campaign Group",
			Long:  "Retrieves the list of campaigns that belong to the specified campaign group. Results are paginated and can optionally be filtered by campaign status.\n\n**Note:** The `campaignStatus` filter is case-insensitive. Allowed values are `Draft`, `Running`, `Pending`, `Paused`, `Completed`, `Ended`. Unknown values will result in a 400 response.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v3/campaign-management/campaign-groups/{campaignGroupName}/campaigns")
				req.PathParam("campaignGroupName", campaignGroupName)
				req.QueryParam("page", page)
				req.QueryParam("pageSize", pageSize)
				req.QueryParam("campaignStatus", campaignStatus)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&campaignGroupName, "campaign-group-name", "", "The name of the campaign group whose campaigns are to be retrieved. Case-insensitive matching.   **Allowed characters:** - `A-Z`, `a-z`, `0-9`, `_` (underscore), space  **Allowed Length** `1..64`")
		cmd.MarkFlagRequired("campaign-group-name")
		cmd.Flags().StringVar(&page, "page", "", "The page number of the result set to retrieve (1-based).")
		cmd.Flags().StringVar(&pageSize, "page-size", "", "The number of campaigns to return per page. Must be between 1 and 100.")
		cmd.Flags().StringVar(&campaignStatus, "campaign-status", "", "Optional filter for campaign status. Case-insensitive. Allowed values: `Draft`, `Running`, `Pending`, `Paused`, `Completed`, `Ended`.")
		campaignGroupCmd.AddCommand(cmd)
	}

}
