// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"
	"strconv"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print
var _ = strconv.Itoa

var dataSourcesCmd = &cobra.Command{
	Use:   "data-sources",
	Short: "DataSources commands",
}

func init() {
	cmd.CcCmd.AddCommand(dataSourcesCmd)

	{ // register
		var audience string
		var nonce string
		var schemaId string
		var subject string
		var tokenLifetimeMinutes int64
		var url string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "register",
			Short: "Register a Data Source",
			Long:  "Register a data source with the Webex BYODS system. Authenticate using a Service App with the `spark-admin:datasource_write` scope.\nSchema IDs determine the types of data Webex sends to the DAP and the expected responses. Use the Data Source Schemas endpoints to inspect the available schemas.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/dataSources")
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyString("audience", audience)
					req.BodyString("nonce", nonce)
					req.BodyString("schemaId", schemaId)
					req.BodyString("subject", subject)
					req.BodyInt("tokenLifetimeMinutes", tokenLifetimeMinutes, cmd.Flags().Changed("token-lifetime-minutes"))
					req.BodyString("url", url)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&audience, "audience", "", "")
		cmd.Flags().StringVar(&nonce, "nonce", "", "")
		cmd.Flags().StringVar(&schemaId, "schema-id", "", "")
		cmd.Flags().StringVar(&subject, "subject", "", "")
		cmd.Flags().Int64Var(&tokenLifetimeMinutes, "token-lifetime-minutes", 0, "")
		cmd.Flags().StringVar(&url, "url", "", "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		dataSourcesCmd.AddCommand(cmd)
	}

	{ // get-all
		cmd := &cobra.Command{
			Use:   "get-all",
			Short: "Retrieve All Data Sources",
			Long:  "Lists all data sources registered by the Service App. Requires the `spark-admin:datasource_read` scope.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/dataSources")
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		dataSourcesCmd.AddCommand(cmd)
	}

	{ // get-schemas
		cmd := &cobra.Command{
			Use:   "get-schemas",
			Short: "Retrieve Data Source Schemas",
			Long:  `Lists the available data source schemas. A valid API access token is required, but no specific scope is needed.`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/dataSources/schemas")
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		dataSourcesCmd.AddCommand(cmd)
	}

	{ // get-schema
		var schemaId string
		cmd := &cobra.Command{
			Use:   "get-schema",
			Short: "Retrieve Details of a Specific Data Source Schema",
			Long:  `Retrieves details for a specific data source schema by schema ID. A valid API access token is required, but no specific scope is needed.`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/dataSources/schemas/{schemaId}")
				req.PathParam("schemaId", schemaId)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&schemaId, "schema-id", "", "The unique identifier for the schema.")
		cmd.MarkFlagRequired("schema-id")
		dataSourcesCmd.AddCommand(cmd)
	}

	{ // delete
		var dataSourceId string
		cmd := &cobra.Command{
			Use:   "delete",
			Short: "Delete a Data Source",
			Long:  "Deletes a data source by ID.\n\nSpecify the data source ID in the `dataSourceId` URI parameter.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "DELETE", "/dataSources/{dataSourceId}")
				req.PathParam("dataSourceId", dataSourceId)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&dataSourceId, "data-source-id", "", "The unique identifier for the data source.")
		cmd.MarkFlagRequired("data-source-id")
		dataSourcesCmd.AddCommand(cmd)
	}

	{ // get
		var dataSourceId string
		cmd := &cobra.Command{
			Use:   "get",
			Short: "Retrieve Data Source Details",
			Long:  "Retrieves details for a data source by ID. Use a Service App token with the `spark-admin:datasource_read` scope.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/dataSources/{dataSourceId}")
				req.PathParam("dataSourceId", dataSourceId)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&dataSourceId, "data-source-id", "", "The unique identifier for the data source.")
		cmd.MarkFlagRequired("data-source-id")
		dataSourcesCmd.AddCommand(cmd)
	}

	{ // update
		var dataSourceId string
		var audience string
		var errorMessage string
		var nonce string
		var schemaId string
		var status string
		var subject string
		var tokenLifetimeMinutes int64
		var url string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "update",
			Short: "Update a Data Source",
			Long:  "Updates a data source. The fields you can update are `audience`, `subject`, `nonce`, `url`, and `tokenLifetimeMinutes`.\nYou can set `status` from `active` to `disabled` only if you provide an `errorMessage`, which may be shown to the customer administrator in Control Hub.\nUpdate tokens before they expire to prevent service interruption.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "PUT", "/dataSources/{dataSourceId}")
				req.PathParam("dataSourceId", dataSourceId)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyString("audience", audience)
					req.BodyString("errorMessage", errorMessage)
					req.BodyString("nonce", nonce)
					req.BodyString("schemaId", schemaId)
					req.BodyString("status", status)
					req.BodyString("subject", subject)
					req.BodyInt("tokenLifetimeMinutes", tokenLifetimeMinutes, cmd.Flags().Changed("token-lifetime-minutes"))
					req.BodyString("url", url)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&dataSourceId, "data-source-id", "", "The unique identifier for the data source.")
		cmd.MarkFlagRequired("data-source-id")
		cmd.Flags().StringVar(&audience, "audience", "", "")
		cmd.Flags().StringVar(&errorMessage, "error-message", "", "")
		cmd.Flags().StringVar(&nonce, "nonce", "", "")
		cmd.Flags().StringVar(&schemaId, "schema-id", "", "")
		cmd.Flags().StringVar(&status, "status", "", "")
		cmd.Flags().StringVar(&subject, "subject", "", "")
		cmd.Flags().Int64Var(&tokenLifetimeMinutes, "token-lifetime-minutes", 0, "")
		cmd.Flags().StringVar(&url, "url", "", "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		dataSourcesCmd.AddCommand(cmd)
	}

}
