// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"
	"strconv"
	"strings"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print
var _ = strconv.Itoa
var _ = strings.Join

var flowsCmd = &cobra.Command{
	Use:   "flows",
	Short: "Flows commands",
}

func init() {
	cmd.CcCmd.AddCommand(flowsCmd)

	{ // list
		var orgid string
		var flowType string
		var ids string
		var page string
		var partialNameSearch string
		var searchBy string
		var size string
		var includePagination string
		var isValidation string
		cmd := &cobra.Command{
			Use:   "list",
			Short: "List Flows or Subflows",
			Long:  "Returns a list of flows in response. Channel-based filtering can be applied with the `searchBy` query parameter (for example, `channelType|telephony`, `channelType|workItem`, `channelType|customMessaging`, `channelType|genericAction`). Channel visibility may be constrained by organization feature flags.\n\nScope: `cjp:config_read`. Roles: [`Organizational Full Admin`, `Supervisor`, `Contact Center Service Admin`, `User Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/flows")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.QueryParam("flowType", flowType)
				req.QueryParam("ids", ids)
				req.QueryParam("ids", ids)
				req.QueryParam("page", page)
				req.QueryParam("partialNameSearch", partialNameSearch)
				req.QueryParam("searchBy", searchBy)
				req.QueryParam("size", size)
				req.QueryParam("includePagination", includePagination)
				req.QueryParam("isValidation", isValidation)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&ids, "ids", "", "Filters results based on a comma-separated list of flow IDs. If provided, only flows with those IDs will be fetched in the response.")
		cmd.Flags().StringVar(&page, "page", "", "Defines the number of the displayed page. The page number starts from 0.")
		cmd.Flags().StringVar(&partialNameSearch, "partial-name-search", "", "Performs a partial string match on the name of the flow. If the flow name contains the given string it will be fetched in the response.")
		cmd.Flags().StringVar(&searchBy, "search-by", "", "Filter expression in the format `<field>|<value>`. Supports searching by `channelType` (for example, `channelType|telephony`, `channelType|workItem`, `channelType|customMessaging`, `channelType|genericAction`).")
		cmd.Flags().StringVar(&size, "size", "", "Defines the number of items to be displayed on a page. If the number specified is more than allowed max page size, the API will automatically adjust the page size to the max page size.")
		cmd.Flags().StringVar(&includePagination, "include-pagination", "", "If set to to true then a different paginated response object containing the page metadata (currentPage, totalRecords, pageSize, totalPages) will be returned. The flow objects will be in an array named \"data\".")
		cmd.Flags().StringVar(&isValidation, "is-validation", "", "If true, validates the existence of flows by ID regardless of the caller's RBAC access. Intended for internal Task Management use cases.")
		flowsCmd.AddCommand(cmd)
	}

	{ // publish
		var orgid string
		var flowId string
		var skipValidation string
		var flowType string
		var trackingId string
		var comment string
		var tagIds []string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "publish",
			Short: "Publish a Flow or Subflow",
			Long:  "Returns the published flow in response.\n\nThe Publish API validates the basic structure of the flows. We recommend manually verifying the published flows before proceeding with live traffic.\n\nScope: `cjp:config_read`. Roles: [`Organizational Full Admin`, `Supervisor`, `Contact Center Service Admin`, `User Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/flow-store/{orgid}/project/{projectId}/flows/{flowId}:publish")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("skipValidation", skipValidation)
				req.QueryParam("flowType", flowType)
				req.Header("TrackingId", trackingId)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyString("comment", comment)
					req.BodyStringSlice("tagIds", tagIds)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&skipValidation, "skip-validation", "", "If true, the flow's pre-publish validation is skipped. Use with care.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&trackingId, "tracking-id", "", "ID for tracking.")
		cmd.Flags().StringVar(&comment, "comment", "", "")
		cmd.Flags().StringSliceVar(&tagIds, "tag-ids", nil, "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // lock
		var orgid string
		var flowId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "lock",
			Short: "Lock a Flow or Subflow",
			Long:  "Lock a flow to prevent concurrent edits by other users. Locks expire after 15 minutes of inactivity.\n\nScope: `cjp:config_write`. Roles: [`Organizational Full Admin`, `Contact Center Service Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/flow-store/{orgid}/project/{projectId}/flows/{flowId}:lock")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("flowType", flowType)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // unlock
		var orgid string
		var flowId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "unlock",
			Short: "Unlock a Flow or Subflow",
			Long:  "Release the lock on a flow to allow other users to edit it.\n\nScope: `cjp:config_write`. Roles: [`Organizational Full Admin`, `Contact Center Service Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/flow-store/{orgid}/project/{projectId}/flows/{flowId}:unlock")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("flowType", flowType)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // validate
		var orgid string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "validate",
			Short: "Validate a Flow",
			Long:  "Dry-run validate a flow definition without persisting it. Use this to check correctness before importing.\n\nNote: validation is more lenient than import. A flow that passes `:validate` can still be rejected by `:import` (for example, a missing start activity), so a successful validation does not guarantee a successful import.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/flow-store/{orgid}/project/{projectId}/v2/flows:validate")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // import
		var orgid string
		var overwrite string
		var flowType string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "import",
			Short: "Import a Flow",
			Long:  "Import a new flow from a flow definition. Creates the flow in draft state and returns the assigned flow metadata, including `flowId`.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/flow-store/{orgid}/project/{projectId}/v2/flows:import")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.QueryParam("overwrite", overwrite)
				req.QueryParam("flowType", flowType)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&overwrite, "overwrite", "", "If true, replaces an existing flow with the same name. Defaults to false.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // get
		var orgid string
		var flowId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "get",
			Short: "Get a Flow",
			Long:  "Retrieve the current draft of a flow as a flow document. To fetch a specific published version, use the `:export` endpoint.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/v2/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("flowType", flowType)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "Flow ID.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // save-draft
		var orgid string
		var flowId string
		var expectedVersion string
		var flowType string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "save-draft",
			Short: "Save a Flow Draft",
			Long:  "Save a complete flow document as the current draft, replacing the existing draft. Pass `expectedVersion` as a query parameter to enable optimistic locking; the request fails with `409 Conflict` if the server-side version does not match. Omit `expectedVersion` to skip the check.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/flow-store/{orgid}/project/{projectId}/v2/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("expectedVersion", expectedVersion)
				req.QueryParam("flowType", flowType)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "Flow ID.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&expectedVersion, "expected-version", "", "Expected current draft version for optimistic locking. The request fails with 409 Conflict if the server-side version does not match. Omit to skip the check.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // patch-draft
		var orgid string
		var flowId string
		var expectedVersion string
		var flowType string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "patch-draft",
			Short: "Patch a Flow Draft",
			Long:  "Apply partial updates to an existing flow draft without replacing the entire document. The patch body is a Patch Draft Contract \u2014 server-side merge, idempotent, and re-validated after the merge. The patch is rejected if the merged document fails validation, so the draft is never left in a broken state. The body may also include top-level overrides such as `name` and `description`.\n\nPass `expectedVersion` as a query parameter to enable optimistic locking; the request fails with `409 Conflict` if the server-side version does not match. Omit `expectedVersion` to skip the check.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "PATCH", "/flow-store/{orgid}/project/{projectId}/v2/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("expectedVersion", expectedVersion)
				req.QueryParam("flowType", flowType)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "Flow ID.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&expectedVersion, "expected-version", "", "Expected current draft version for optimistic locking. The request fails with 409 Conflict if the server-side version does not match. Omit to skip the check.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // validate-draft
		var orgid string
		var flowId string
		var versionId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "validate-draft",
			Short: "Validate an Existing Flow Draft",
			Long:  "Validate the current draft of an existing flow (read-only operation).\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/v2/flows/{flowId}:validate")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("versionId", versionId)
				req.QueryParam("flowType", flowType)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&versionId, "version-id", "", "Version to validate. Use 'draft' for the current draft, or a specific version ObjectId.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // export
		var orgid string
		var flowId string
		var version string
		var flowType string
		cmd := &cobra.Command{
			Use:   "export",
			Short: "Export a Flow",
			Long:  "Export a flow as a flow document for backup, migration, or version control.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/flow-store/{orgid}/project/{projectId}/v2/flows/{flowId}:export")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("version", version)
				req.QueryParam("flowType", flowType)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&version, "version", "", "Version to export. Use 'latest' for the most recent published version, 'draft' for the working copy, or a specific version ObjectId.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // list-2
		var orgid string
		var flowType string
		var ids string
		var page string
		var partialNameSearch string
		var searchBy string
		var size string
		var includePagination string
		var isValidation string
		cmd := &cobra.Command{
			Use:   "list-2",
			Short: "List Flows or Subflows",
			Long:  "Returns a list of flows in response. Channel-based filtering can be applied with the `searchBy` query parameter (for example, `channelType|telephony`, `channelType|workItem`, `channelType|customMessaging`, `channelType|genericAction`). Channel visibility may be constrained by organization feature flags. If associatedChannels key is missing or empty, it will be treated as telephony flow.\n\nScope: `cjp:config_read`. Roles: [`Organizational Full Admin`, `Supervisor`, `Contact Center Service Admin`, `User Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/flows")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.QueryParam("flowType", flowType)
				req.QueryParam("ids", ids)
				req.QueryParam("ids", ids)
				req.QueryParam("page", page)
				req.QueryParam("partialNameSearch", partialNameSearch)
				req.QueryParam("searchBy", searchBy)
				req.QueryParam("size", size)
				req.QueryParam("includePagination", includePagination)
				req.QueryParam("isValidation", isValidation)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&ids, "ids", "", "Filters results based on a comma-separated list of flow IDs. If provided, only flows with those IDs will be fetched in the response.")
		cmd.Flags().StringVar(&page, "page", "", "Defines the number of the displayed page. The page number starts from 0.")
		cmd.Flags().StringVar(&partialNameSearch, "partial-name-search", "", "Performs a partial string match on the name of the flow. If the flow name contains the given string it will be fetched in the response.")
		cmd.Flags().StringVar(&searchBy, "search-by", "", "Filter expression in the format `<field>|<value>`. Supports searching by `channelType` (for example, `channelType|telephony`, `channelType|workItem`, `channelType|customMessaging`, `channelType|genericAction`).")
		cmd.Flags().StringVar(&size, "size", "", "Defines the number of items to be displayed on a page. If the number specified is more than allowed max page size, the API will automatically adjust the page size to the max page size.")
		cmd.Flags().StringVar(&includePagination, "include-pagination", "", "If set to true then a different paginated response object containing the page metadata (currentPage, totalRecords, pageSize, totalPages) will be returned. The flow objects will be in an array named \"data\".")
		cmd.Flags().StringVar(&isValidation, "is-validation", "", "If true, validates the existence of flows by ID regardless of the caller's RBAC access. Intended for internal Task Management use cases.")
		flowsCmd.AddCommand(cmd)
	}

	{ // publish-2
		var orgid string
		var flowId string
		var skipValidation string
		var flowType string
		var trackingId string
		var comment string
		var tagIds []string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "publish-2",
			Short: "Publish a Flow or Subflow",
			Long:  "Returns the published flow in response.\n\nThe Publish API validates the basic structure of the flows. We recommend manually verifying the published flows before proceeding with live traffic.\n\nScope: `cjp:config_write`. Roles: [`Organizational Full Admin`, `Supervisor`, `Contact Center Service Admin`, `User Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/{orgid}/project/{projectId}/flows/{flowId}:publish")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("skipValidation", skipValidation)
				req.QueryParam("flowType", flowType)
				req.Header("TrackingId", trackingId)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyString("comment", comment)
					req.BodyStringSlice("tagIds", tagIds)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&skipValidation, "skip-validation", "", "If true, the flow's pre-publish validation is skipped. Use with care.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&trackingId, "tracking-id", "", "ID for tracking.")
		cmd.Flags().StringVar(&comment, "comment", "", "")
		cmd.Flags().StringSliceVar(&tagIds, "tag-ids", nil, "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // lock-2
		var orgid string
		var flowId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "lock-2",
			Short: "Lock a Flow or Subflow",
			Long:  "Lock a flow to prevent concurrent edits by other users. Locks expire after 15 minutes of inactivity.\n\nScope: `cjp:config_write`. Roles: [`Organizational Full Admin`, `Contact Center Service Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/{orgid}/project/{projectId}/flows/{flowId}:lock")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("flowType", flowType)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // unlock-2
		var orgid string
		var flowId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "unlock-2",
			Short: "Unlock a Flow or Subflow",
			Long:  "Release the lock on a flow to allow other users to edit it.\n\nScope: `cjp:config_write`. Roles: [`Organizational Full Admin`, `Contact Center Service Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/{orgid}/project/{projectId}/flows/{flowId}:unlock")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("flowType", flowType)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // validate-2
		var orgid string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "validate-2",
			Short: "Validate a Flow or Subflow",
			Long:  "Dry-run validate a flow/subflow definition without persisting it. Use this to check correctness before importing. Include `associatedChannels` to preserve the channel metadata that import and export payloads round-trip. Validation requests where `associatedChannels` is missing or empty are treated as telephony flows, and dry-run validation does not derive the effective channel from `associatedChannels`.\n\nNote: validation is more lenient than import. A flow that passes `:validate` can still be rejected by `:import` (for example, a missing start activity), so a successful validation does not guarantee a successful import.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/{orgid}/project/{projectId}/v2/flows:validate")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // import-2
		var orgid string
		var overwrite string
		var flowType string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "import-2",
			Short: "Import a Flow or Subflow",
			Long:  "Import a new flow/subflow from a flow definition. Creates the flow/subflow in draft state and returns the assigned flow metadata, including `flowId`. Include `associatedChannels` in the payload when the flow contains channel-specific activities (for example, `customMessaging`) so channel references can be resolved correctly during import. If `associatedChannels` is missing or empty, the import is treated as a telephony flow. For `FLOW` imports, blank or whitespace-only `associatedChannels[].channelType` values are rejected.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/{orgid}/project/{projectId}/v2/flows:import")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.QueryParam("overwrite", overwrite)
				req.QueryParam("flowType", flowType)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&overwrite, "overwrite", "", "If true, replaces an existing flow with the same name. Defaults to false.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // get-2
		var orgid string
		var flowId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "get-2",
			Short: "Get a Flow or Subflow",
			Long:  "Retrieve the current draft of a flow/subflow as a flow document. To fetch a specific published version, use the `:export` endpoint. The response includes channel metadata (for example, `associatedChannels`) used by channel-specific activities such as `customMessaging`. If `associatedChannels` is missing or empty, the flow is treated as telephony.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/v2/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("flowType", flowType)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "Flow ID.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // save-draft-2
		var orgid string
		var flowId string
		var expectedVersion string
		var flowType string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "save-draft-2",
			Short: "Save a Flow or Subflow Draft",
			Long:  "Save a complete flow/subflow document as the current draft, replacing the existing draft. Submitted `associatedChannels` values are not persisted on save; the draft preserves the existing stored channel metadata. Omitting `associatedChannels` does not default an existing flow to telephony. Pass `expectedVersion` as a query parameter to enable optimistic locking; the request fails with `409 Conflict` if the server-side version does not match. Omit `expectedVersion` to skip the check.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/{orgid}/project/{projectId}/v2/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("expectedVersion", expectedVersion)
				req.QueryParam("flowType", flowType)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "Flow ID.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&expectedVersion, "expected-version", "", "Expected current draft version for optimistic locking. The request fails with 409 Conflict if the server-side version does not match. Omit to skip the check.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // patch-draft-2
		var orgid string
		var flowId string
		var expectedVersion string
		var flowType string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "patch-draft-2",
			Short: "Patch a Flow or Subflow Draft",
			Long:  "Apply partial updates to an existing flow/subflow draft without replacing the entire document. The patch body is a Patch Draft Contract \u2014 server-side merge, idempotent, and re-validated after the merge. The patch is rejected if the merged document fails validation, so the draft is never left in a broken state. The body may also include top-level overrides such as `name` and `description`. Submitted `associatedChannels` values are not persisted on patch; the draft preserves the existing stored channel metadata.\n\nPass `expectedVersion` as a query parameter to enable optimistic locking; the request fails with `409 Conflict` if the server-side version does not match. Omit `expectedVersion` to skip the check.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "PATCH", "/{orgid}/project/{projectId}/v2/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("expectedVersion", expectedVersion)
				req.QueryParam("flowType", flowType)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "Flow ID.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&expectedVersion, "expected-version", "", "Expected current draft version for optimistic locking. The request fails with 409 Conflict if the server-side version does not match. Omit to skip the check.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		flowsCmd.AddCommand(cmd)
	}

	{ // validate-draft-2
		var orgid string
		var flowId string
		var versionId string
		var flowType string
		cmd := &cobra.Command{
			Use:   "validate-draft-2",
			Short: "Validate an Existing Flow or Subflow Draft",
			Long:  "Validate the current draft of an existing flow/subflow (read-only operation). Validation reads the draft as stored. Drafts where `associatedChannels` is missing or empty are treated as telephony flows, and validation does not derive the effective channel from `associatedChannels`.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/v2/flows/{flowId}:validate")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("versionId", versionId)
				req.QueryParam("flowType", flowType)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&versionId, "version-id", "", "Version to validate. Use 'draft' for the current draft, or a specific version ObjectId.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // export-2
		var orgid string
		var flowId string
		var version string
		var flowType string
		cmd := &cobra.Command{
			Use:   "export-2",
			Short: "Export a Flow or Subflow",
			Long:  "Export a flow/subflow as a flow document for backup, migration, or version control. The exported payload includes `associatedChannels` metadata to preserve channel-specific activity behavior (for example, `customMessaging`) during re-import. If `associatedChannels` is missing or empty, the flow is treated as telephony.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/v2/flows/{flowId}:export")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("version", version)
				req.QueryParam("flowType", flowType)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&version, "version", "", "Version to export. Use 'latest' for the most recent published version, 'draft' for the working copy, or a specific version ObjectId.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

	{ // search
		var orgid string
		var query string
		var flowType string
		var page string
		var size string
		var keyValueFilter string
		cmd := &cobra.Command{
			Use:   "search",
			Short: "Search Flows",
			Long:  "Returns a list of flows in response. The search is case-sensitive.\n\nScope: `cjp:config_read`. Roles: [`Organizational Full Admin`, `Supervisor`, `Contact Center Service Admin`, `User Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/{orgid}/project/{projectId}/flows:search")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.QueryParam("query", query)
				req.QueryParam("flowType", flowType)
				req.QueryParam("page", page)
				req.QueryParam("size", size)
				req.QueryParam("keyValueFilter", keyValueFilter)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&query, "query", "", "Searches for flows with the given query. The search is case-sensitive.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW' or 'ALL'. Default value is 'ALL'.")
		cmd.Flags().StringVar(&page, "page", "", "Defines the number of the displayed page. The page number starts from 0.")
		cmd.Flags().StringVar(&size, "size", "", "Defines the number of items to be displayed on a page. If the number specified is more than allowed max page size, the API will automatically adjust the page size to the max page size.")
		cmd.Flags().StringVar(&keyValueFilter, "key-value-filter", "", "Filters results based on key-value pairs. Format: 'key1|value1,key2|value2'. This will add a filter on normalizedFlow collection directly instead of running query on atlas.")
		flowsCmd.AddCommand(cmd)
	}

	{ // delete
		var orgid string
		var flowId string
		var force string
		var skipRsEpcheck string
		var flowType string
		cmd := &cobra.Command{
			Use:   "delete",
			Short: "Delete a Flow or Subflow",
			Long:  "Permanently deletes a flow or subflow. Flows deleted via this API are removed permanently and cannot be recovered.\n\nScope: `cjp:config_write`. Roles: [`Organizational Full Admin`, `Contact Center Service Admin`]",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "DELETE", "/{orgid}/project/{projectId}/flows/{flowId}")
				req.PathParam("orgid", orgid)
				req.PathParam("projectId", "5e5c9ad6d61f870d6d778c1b")
				req.PathParam("flowId", flowId)
				req.QueryParam("force", force)
				req.QueryParam("skipRsEPCheck", skipRsEpcheck)
				req.QueryParam("flowType", flowType)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&flowId, "flow-id", "", "ID of the flow/subflow to delete.")
		cmd.MarkFlagRequired("flow-id")
		cmd.Flags().StringVar(&force, "force", "", "If 'yes', the flow is deleted even if it is still referenced by other entities. Defaults to 'no'.")
		cmd.Flags().StringVar(&skipRsEpcheck, "skip-rs-epcheck", "", "If true, skips the check for routing strategy and entry point associations before deleting the flow.")
		cmd.Flags().StringVar(&flowType, "flow-type", "", "Either of 'FLOW' or 'SUBFLOW'.")
		flowsCmd.AddCommand(cmd)
	}

}
