// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"
	"strconv"
	"strings"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print
var _ = strconv.Itoa
var _ = strings.Join

var functionsCmd = &cobra.Command{
	Use:   "functions",
	Short: "Functions commands",
}

func init() {
	cmd.CcCmd.AddCommand(functionsCmd)

	{ // list
		var orgid string
		var isPartialMatch string
		var isCaseSensitive string
		var name string
		var language string
		var status string
		var sortBy string
		var page string
		var size string
		var ids string
		var fields string
		var isValidation string
		cmd := &cobra.Command{
			Use:   "list",
			Short: "List Custom Functions",
			Long:  "List or search custom functions in the organization. Without filters, returns all custom functions. Supports filtering by name, language, and status, plus sorting and pagination.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/{orgid}/functions")
				req.PathParam("orgid", orgid)
				req.QueryParam("isPartialMatch", isPartialMatch)
				req.QueryParam("isCaseSensitive", isCaseSensitive)
				req.QueryParam("name", name)
				req.QueryParam("language", language)
				req.QueryParam("status", status)
				req.QueryParam("sortBy", sortBy)
				req.QueryParam("page", page)
				req.QueryParam("size", size)
				req.QueryParam("ids", ids)
				req.QueryParam("fields", fields)
				req.QueryParam("isValidation", isValidation)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&isPartialMatch, "is-partial-match", "", "Whether to search with partial matches. If `false`, search/filter is based on exact match.")
		cmd.Flags().StringVar(&isCaseSensitive, "is-case-sensitive", "", "Whether the search should be case-sensitive. Currently applicable only to the `name` field.")
		cmd.Flags().StringVar(&name, "name", "", "Filter by function name.")
		cmd.Flags().StringVar(&language, "language", "", "Filter by programming language.")
		cmd.Flags().StringVar(&status, "status", "", "Filter by one or more function statuses (comma-separated, no spaces). Case-sensitive.")
		cmd.Flags().StringVar(&sortBy, "sort-by", "", "Comma-separated fields with order. Supported fields (case-sensitive): `name`, `language`, `status`, `lastModifiedDate`. Prefix a field with `-` for descending order; no prefix means ascending.")
		cmd.Flags().StringVar(&page, "page", "", "Zero-based page number for the paginated query.")
		cmd.Flags().StringVar(&size, "size", "", "Number of results per page.")
		cmd.Flags().StringVar(&ids, "ids", "", "Comma-separated list of function IDs to fetch.")
		cmd.Flags().StringVar(&fields, "fields", "", "Comma-separated list of function fields to include in the response.")
		cmd.Flags().StringVar(&isValidation, "is-validation", "", "Used by the Tenant Management team to validate the existence of functions with given IDs regardless of the user's RBAC access.")
		functionsCmd.AddCommand(cmd)
	}

	{ // create
		var orgid string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "create",
			Short: "Create a Custom Function",
			Long:  "Create a new custom function. The source code is provided as an escaped string and the runtime defaults to the highest supported runtime for the given language.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions")
				req.PathParam("orgid", orgid)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		functionsCmd.AddCommand(cmd)
	}

	{ // get
		var orgid string
		var id string
		var versionOrTag string
		var metaDataOnly string
		cmd := &cobra.Command{
			Use:   "get",
			Short: "Get a Custom Function",
			Long:  "Retrieve a custom function by its ID. Use `versionOrTag` to fetch a specific published version, or omit it to get the draft.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/{orgid}/functions/{id}")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				req.QueryParam("versionOrTag", versionOrTag)
				req.QueryParam("metaDataOnly", metaDataOnly)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "Custom function ID. Hexadecimal ObjectId returned by the create or list APIs.")
		cmd.MarkFlagRequired("id")
		cmd.Flags().StringVar(&versionOrTag, "version-or-tag", "", "Version number or publish tag of the source code to return (for example, `Dev`, `Live`, or `2`). If omitted, the draft version is returned.")
		cmd.Flags().StringVar(&metaDataOnly, "meta-data-only", "", "If `true`, returns only metadata and excludes source code. If `false` or omitted, returns both metadata and source code.")
		functionsCmd.AddCommand(cmd)
	}

	{ // update
		var orgid string
		var id string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "update",
			Short: "Update a Custom Function",
			Long:  "Update an existing custom function by ID. Replaces the draft source code and metadata with the supplied body.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "PUT", "/v1/{orgid}/functions/{id}")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "Custom function ID.")
		cmd.MarkFlagRequired("id")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		functionsCmd.AddCommand(cmd)
	}

	{ // delete
		var orgid string
		var id string
		var isForceDeletion string
		cmd := &cobra.Command{
			Use:   "delete",
			Short: "Delete a Custom Function",
			Long:  "Delete a custom function by ID. Use `isForceDeletion=true` to delete even when the function is referenced by one or more flows.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "DELETE", "/v1/{orgid}/functions/{id}")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				req.QueryParam("isForceDeletion", isForceDeletion)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "Custom function ID.")
		cmd.MarkFlagRequired("id")
		cmd.Flags().StringVar(&isForceDeletion, "is-force-deletion", "", "If `true`, deletes the function regardless of its usage in flows.")
		functionsCmd.AddCommand(cmd)
	}

	{ // import
		var orgid string
		var overwrite string
		var associatedRcs string
		cmd := &cobra.Command{
			Use:   "import",
			Short: "Import a Custom Function",
			Long:  "Import a custom function from a previously exported function-definition JSON file, uploaded as the multipart `file` part (not a zip or base64 envelope). Use `overwrite=true` to replace any existing function with the same name.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions:import")
				req.PathParam("orgid", orgid)
				req.QueryParam("overwrite", overwrite)
				req.QueryParam("associatedRcs", associatedRcs)
				req.QueryParam("associatedRcs", associatedRcs)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&overwrite, "overwrite", "", "If `true`, overwrites a function with the same name if one already exists.")
		cmd.Flags().StringVar(&associatedRcs, "associated-rcs", "", "Optional list of associated routing-context IDs.")
		functionsCmd.AddCommand(cmd)
	}

	{ // unlock
		var orgid string
		var id string
		cmd := &cobra.Command{
			Use:   "unlock",
			Short: "Unlock a Custom Function",
			Long:  "Release the edit lock on a custom function so that other users can edit it.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions/{id}:unlock")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "")
		cmd.MarkFlagRequired("id")
		functionsCmd.AddCommand(cmd)
	}

	{ // lock
		var orgid string
		var id string
		cmd := &cobra.Command{
			Use:   "lock",
			Short: "Lock a Custom Function",
			Long:  "Acquire an edit lock on a custom function to prevent concurrent writes by other users.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions/{id}:lock")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "")
		cmd.MarkFlagRequired("id")
		functionsCmd.AddCommand(cmd)
	}

	{ // test
		var orgid string
		var id string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "test",
			Short: "Test a Custom Function",
			Long:  "Execute a custom function with a test payload. Implicitly publishes the latest draft first, so the run uses the most recent source code.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions/{id}:test")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "")
		cmd.MarkFlagRequired("id")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		functionsCmd.AddCommand(cmd)
	}

	{ // publish
		var orgid string
		var id string
		var tags []string
		var comment string
		var key_0 int64
		var key_1 float64
		var key_2 float64
		var key_3 float64
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "publish",
			Short: "Publish a Custom Function",
			Long:  "Publish the latest draft of a custom function under one or more tags (`Dev`, `Test`, `Latest`, `Live`). Ensure the function has been created or updated before calling this API.\n\nScope: `cjp:config_write`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions/{id}:publish")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyStringSlice("tags", tags)
					req.BodyString("comment", comment)
					req.BodyInt("key_0", key_0, cmd.Flags().Changed("key_0"))
					req.BodyFloat("key_1", key_1, cmd.Flags().Changed("key_1"))
					req.BodyFloat("key_2", key_2, cmd.Flags().Changed("key_2"))
					req.BodyFloat("key_3", key_3, cmd.Flags().Changed("key_3"))
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "")
		cmd.MarkFlagRequired("id")
		cmd.Flags().StringSliceVar(&tags, "tags", nil, "")
		cmd.Flags().StringVar(&comment, "comment", "", "")
		cmd.Flags().Int64Var(&key_0, "key_0", 0, "")
		cmd.Flags().Float64Var(&key_1, "key_1", 0, "")
		cmd.Flags().Float64Var(&key_2, "key_2", 0, "")
		cmd.Flags().Float64Var(&key_3, "key_3", 0, "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		functionsCmd.AddCommand(cmd)
	}

	{ // export
		var orgid string
		var id string
		var versionOrTag string
		cmd := &cobra.Command{
			Use:   "export",
			Short: "Export a Custom Function",
			Long:  "Export a custom function for the given version or publish tag. Returns the plain function-definition JSON (name, language, runtime, description, source code, inputs, and outputs), suitable for re-importing via the import API.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/{orgid}/functions/{id}:export")
				req.PathParam("orgid", orgid)
				req.PathParam("id", id)
				req.QueryParam("versionOrTag", versionOrTag)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&id, "id", "", "")
		cmd.MarkFlagRequired("id")
		cmd.Flags().StringVar(&versionOrTag, "version-or-tag", "", "Version number or publish tag of the source code to export. If omitted, the latest published version is exported.")
		functionsCmd.AddCommand(cmd)
	}

	{ // list-options
		var orgid string
		var language string
		var runtime string
		cmd := &cobra.Command{
			Use:   "list-options",
			Short: "List Function Options",
			Long:  "List the supported programming languages, runtimes, and corresponding wrapper code for custom functions. Filter by `language` or `runtime` to narrow the result.\n\nScope: `cjp:config_read`",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/{orgid}/functions/options")
				req.PathParam("orgid", orgid)
				req.QueryParam("language", language)
				req.QueryParam("runtime", runtime)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgid, "orgid", "", "Organization ID.")
		cmd.MarkFlagRequired("orgid")
		cmd.Flags().StringVar(&language, "language", "", "Filter by programming language (for example, `js`, `py`).")
		cmd.Flags().StringVar(&runtime, "runtime", "", "Filter by runtime (for example, `nodejs22.x`, `python3.13`).")
		functionsCmd.AddCommand(cmd)
	}

}
