// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print

var searchMetadataCmd = &cobra.Command{
	Use:   "search-metadata",
	Short: "SearchMetadata commands",
}

func init() {
	cmd.CcCmd.AddCommand(searchMetadataCmd)

	{ // get
		var xOrganizationId string
		var trackingId string
		cmd := &cobra.Command{
			Use:   "get",
			Short: "Get Search Metadata",
			Long:  "Returns schema metadata for the Webex Contact Center Search GraphQL API, describing supported queries, fields, nested structures, data types, filters, sorting options, grouping capabilities, and aggregation operations.\n\n**Authentication & Authorization:**\n- **Required Scopes:** `cjp:config` or `cjp:config_read`\n\nAn asterisk (*) in the rendered response schema indicates a required property.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/search/v2/meta")
				req.Header("X-ORGANIZATION-ID", xOrganizationId)
				req.Header("TrackingId", trackingId)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&xOrganizationId, "x-organization-id", "", "Organization ID to use for this operation. If unspecified, inferred from token. Token must have permission to interact with this organization.")
		cmd.Flags().StringVar(&trackingId, "tracking-id", "", "Tracking ID to use for this operation, for traceability, debugging, and error reporting purposes. ")
		searchMetadataCmd.AddCommand(cmd)
	}

}
