// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package cc

import (
	"fmt"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print

var usageReportsCmd = &cobra.Command{
	Use:   "usage-reports",
	Short: "UsageReports commands",
}

func init() {
	cmd.CcCmd.AddCommand(usageReportsCmd)

	{ // get-available-types
		cmd := &cobra.Command{
			Use:   "get-available-types",
			Short: "Get available resource types",
			Long:  `Returns the list of available resource types that can be used for report generation, along with available data dates.`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/usage-reports/resource-types")
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		usageReportsCmd.AddCommand(cmd)
	}

	{ // create
		var resourceType string
		var startDate string
		var endDate string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "create",
			Short: "Create usage report",
			Long:  "Creates a new usage report for the specified organization, resource type,\nand date range. The report is generated asynchronously in the background.\n\nA single **usage report (reportId)** is always created for each request.\nDepending on the requested date range, the report may contain **one or more\nreport files**, each representing a sub-range of the overall time period.\n\nWhen the requested date range spans **more than 30 days**, the overall range\nis **automatically split by natural calendar months**, and **multiple report\nfiles** are generated under the same report.\n\n**Examples:**\n\n- Requested range: `2025-12-23` ~ `2026-03-20`\n  - Generated result:\n    - Report ID: single report\n    - Report files:\n      - `2025-12-23` ~ `2025-12-31`\n      - `2026-01-01` ~ `2026-01-31`\n      - `2026-02-01` ~ `2026-02-28`\n      - `2026-03-01` ~ `2026-03-20`\n\n- Requested range: `2025-12-23` ~ `2026-01-21`\n  - Generated result:\n    - Report ID: single report\n    - Report files:\n      - `2025-12-23` ~ `2026-01-21`\n\n**Important Notes:**\n- Only one usage report can be processed at a time for the same organization.\n  If there is an ongoing report, new report creation requests will be rejected.\n",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "POST", "/v1/usage-reports")
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyString("resourceType", resourceType)
					req.BodyString("startDate", startDate)
					req.BodyString("endDate", endDate)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&resourceType, "resource-type", "", "")
		cmd.Flags().StringVar(&startDate, "start-date", "", "")
		cmd.Flags().StringVar(&endDate, "end-date", "", "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		usageReportsCmd.AddCommand(cmd)
	}

	{ // list
		var resourceType string
		var createdAfter string
		var createdBefore string
		cmd := &cobra.Command{
			Use:   "list",
			Short: "List usage reports",
			Long:  "Retrieves a list of usage reports for the organization. Supports optional filtering by resource type and creation date range.\n\nEach report has a `reportId` and may contain one or more generated files in `reportFiles[]`. For long date ranges, the service can split results by calendar month to avoid creating a single very large download. For example, a 12-month report can return up to 12 report files, and a 36-month report can return up to 36 report files.\n\nUse `reportId` to retrieve the overall report status, list the generated files, or delete the report. Use each file's `fileId` or `downloadUrl` to download that specific file. The download API does not accept `reportId`.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/usage-reports")
				req.QueryParam("resourceType", resourceType)
				req.QueryParam("createdAfter", createdAfter)
				req.QueryParam("createdBefore", createdBefore)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&resourceType, "resource-type", "", "Filter by resource type")
		cmd.Flags().StringVar(&createdAfter, "created-after", "", "Filter reports created after this timestamp (ISO 8601 format)")
		cmd.Flags().StringVar(&createdBefore, "created-before", "", "Filter reports created before this timestamp (ISO 8601 format)")
		usageReportsCmd.AddCommand(cmd)
	}

	{ // get
		var reportId string
		cmd := &cobra.Command{
			Use:   "get",
			Short: "Get usage report details",
			Long:  `Retrieves detailed information for a specific usage report.`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/usage-reports/{reportId}")
				req.PathParam("reportId", reportId)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&reportId, "report-id", "", "Usage report ID")
		cmd.MarkFlagRequired("report-id")
		usageReportsCmd.AddCommand(cmd)
	}

	{ // delete
		var reportId string
		cmd := &cobra.Command{
			Use:   "delete",
			Short: "Delete usage report",
			Long:  `Deletes the specified usage report and its associated file. This operation cannot be undone.`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "DELETE", "/v1/usage-reports/{reportId}")
				req.PathParam("reportId", reportId)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&reportId, "report-id", "", "Usage report ID")
		cmd.MarkFlagRequired("report-id")
		usageReportsCmd.AddCommand(cmd)
	}

	{ // download-file
		var fileId string
		cmd := &cobra.Command{
			Use:   "download-file",
			Short: "Download usage report file",
			Long:  "Downloads one completed report file as a binary stream.\n\nUse the `fileId` returned in the report's `reportFiles` array. A `reportId` identifies the overall report and cannot be used with this endpoint. Usage Reports can cover up to 36 months of raw data, so large date ranges may be split into one file per calendar month. This keeps individual compressed files more manageable and avoids requiring customers to download a single very large file. If a report contains multiple files, call this endpoint once for each `fileId`.\n\nPassing a `reportId` to this endpoint returns `404` because the path parameter expects a file-level identifier.\n\nThe Developer Portal may not handle binary downloads reliably. Use Postman, curl, or a programmatic API client to download the file.\n\n**Note:** Both file and download URLs expire 7 days after report completion.\n",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CcBaseURL, "GET", "/v1/usage-reports/{fileId}/download")
				req.PathParam("fileId", fileId)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(false)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&fileId, "file-id", "", "ID of the specific report file to download. Use fileId, not reportId.")
		cmd.MarkFlagRequired("file-id")
		usageReportsCmd.AddCommand(cmd)
	}

}
