// Code generated by codegen/generate_cli.py; DO NOT EDIT.

package admin

import (
	"fmt"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print

var analyticsCmd = &cobra.Command{
	Use:   "analytics",
	Short: "Analytics commands",
}

func init() {
	cmd.AdminCmd.AddCommand(analyticsCmd)

	{ // historical-data-related-messaging
		var from string
		var to string
		cmd := &cobra.Command{
			Use:   "historical-data-related-messaging",
			Short: "Historical Data related to Messaging",
			Long: `Returns daily aggregates of various metrics related to Webex messaging.

<div><Callout type="error">The base URL for these APIs is **analytics.webexapis.com**, which does not work with the **Try It** feature. </Callout></div>`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CallingBaseURL, "GET", "/v1/analytics/messagingMetrics/dailyTotals")
				req.QueryParam("from", from)
				req.QueryParam("to", to)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(true)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&from, "from", "", "UTC date starting from which the data needs to be returned.")
		cmd.Flags().StringVar(&to, "to", "", "UTC date up to which the data needs to be returned")
		analyticsCmd.AddCommand(cmd)
	}

	{ // historical-data-related-room-devices
		var from string
		var to string
		cmd := &cobra.Command{
			Use:   "historical-data-related-room-devices",
			Short: "Historical Data related to Room Devices",
			Long: `Returns daily aggregates of various metrics related to Room Devices.

<div><Callout type="error">The base URL for these APIs is **analytics.webexapis.com**, which does not work with the **Try It** feature. </Callout></div>`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CallingBaseURL, "GET", "/v1/analytics/roomDeviceMetrics/dailyTotals")
				req.QueryParam("from", from)
				req.QueryParam("to", to)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(true)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&from, "from", "", "Starting UTC Date from which historical data should be returned.")
		cmd.Flags().StringVar(&to, "to", "", "Ending UTC Date for which data should be returned.")
		analyticsCmd.AddCommand(cmd)
	}

	{ // historical-data-related-meetings
		var siteUrl string
		var from string
		var to string
		cmd := &cobra.Command{
			Use:   "historical-data-related-meetings",
			Short: "Historical Data related to Meetings",
			Long: `Return aggregates of various metrics related to meetings for a given Webex site over a specified time range.

<div><Callout type="error">The base URL for these APIs is **analytics.webexapis.com**, which does not work with the **Try It** feature.</Callout></div>`,
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CallingBaseURL, "GET", "/v1/analytics/meetingsMetrics/aggregates")
				req.QueryParam("siteUrl", siteUrl)
				req.QueryParam("from", from)
				req.QueryParam("to", to)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(true)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&siteUrl, "site-url", "", "URL of the Webex site for which historical data is requested.")
		cmd.Flags().StringVar(&from, "from", "", "UTC Date starting from which the data needs to be returned")
		cmd.Flags().StringVar(&to, "to", "", "UTC Date up to which the data needs to be returned")
		analyticsCmd.AddCommand(cmd)
	}

}
