package admin

import (
	"fmt"
	"strings"

	cmd "github.com/Cloverhound/webex-cli/cmd"
	"github.com/Cloverhound/webex-cli/internal/client"
	"github.com/Cloverhound/webex-cli/internal/config"
	"github.com/Cloverhound/webex-cli/internal/output"
	"github.com/spf13/cobra"
)

// Ensure imports are used.
var _ = fmt.Sprintf
var _ = config.Token
var _ = output.Print
var _ = strings.Join

var identityOrgCmd = &cobra.Command{
	Use:   "identity-org",
	Short: "IdentityOrg commands",
}

func init() {
	cmd.AdminCmd.AddCommand(identityOrgCmd)

	{ // get
		var orgId string
		cmd := &cobra.Command{
			Use:   "get",
			Short: "Get an organization",
			Long:  "<br/>\n\n**Authorization**\n\nOAuth token rendered by identity broker.\n\n<br/>\n\nOne of the following OAuth scopes is required:\n\n- `identity:organizations_rw`\n\n- `identity:organizations_read`\n\n<br/>",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CallingBaseURL, "GET", "/identity/organizations/{orgId}")
				req.PathParam("orgId", orgId)
				if config.Paginate() {
					resp, statusCode, err := req.DoPaginated(true)
					if err != nil {
						return err
					}
					return output.Print(resp, statusCode)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgId, "org-id", "", "Webex Identity assigned organization identifier.")
		cmd.MarkFlagRequired("org-id")
		identityOrgCmd.AddCommand(cmd)
	}

	{ // update
		var orgId string
		var schemas []string
		var displayName string
		var preferredLanguage string
		var bodyRaw string
		var bodyFile string
		cmd := &cobra.Command{
			Use:   "update",
			Short: "Update an organization",
			Long:  "<br/>\n\n**Authorization**\n\nOAuth token rendered by identity broker.\n\n<br/>\n\nOne of the following OAuth scopes is required:\n\n- `identity:organizations_rw`\n\n<br/>\n\nThe following administrators can use this API:\n\n- `id_full_admin`\n\n<br/>\n\n**Usage**:\n\n1. Input JSON must contain schema: \"urn:cisco:codev:identity:organization:core:1.0\".",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CallingBaseURL, "PATCH", "/identity/organizations/{orgId}")
				req.PathParam("orgId", orgId)
				if bodyFile != "" {
					if err := req.SetBodyFile(bodyFile); err != nil {
						return err
					}
				} else if bodyRaw != "" {
					req.SetBodyRaw(bodyRaw)
				} else {
					req.BodyStringSlice("schemas", schemas)
					req.BodyString("displayName", displayName)
					req.BodyString("preferredLanguage", preferredLanguage)
				}
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgId, "org-id", "", "Webex Identity assigned organization identifier.")
		cmd.MarkFlagRequired("org-id")
		cmd.Flags().StringSliceVar(&schemas, "schemas", nil, "")
		cmd.Flags().StringVar(&displayName, "display-name", "", "")
		cmd.Flags().StringVar(&preferredLanguage, "preferred-language", "", "")
		cmd.Flags().StringVar(&bodyRaw, "body", "", "Raw JSON body")
		cmd.Flags().StringVar(&bodyFile, "body-file", "", "Path to JSON body file")
		identityOrgCmd.AddCommand(cmd)
	}

	{ // generate-otp
		var orgId string
		var userId string
		cmd := &cobra.Command{
			Use:   "generate-otp",
			Short: "Generate OTP",
			Long:  "This API allows an admin to generate a One-Time Password (OTP) for user accounts with `userNameType` set as `partner-upn`. The OTP is used by users to log in to any Webex application, whereupon they are asked to change their password.\nThe OTP generated by this API has a default length of 6 digits and expires in 7 days.\n\nSeveral OTPs can be active for the same user. When the user successfully uses an OTP, all other OTPs are automatically revoked.\n\nThe creation of OTPs is logged in the [Admin Audit Events](https://developer.webex.com/docs/api/v1/admin-audit-events).\n\n**Possible Error:**\n\n- 403: The request was forbidden. OTP generation is restricted to users with a `userNameType` of `partner-upn`. This error occurs if the user does not meet the required criteria for OTP generation.\n\n**Authorization:**\n\nAn OAuth token issued by the Identity Broker is required to access this endpoint. The token must include one of the following scopes:\n\n- `Identity:one_time_password`\nor\n\n- `Identity:Config`\n\n**Administrator Roles:**\n\nThe following administrators have permission to use this API:\n\n- `Org Full Admin`: Can generate OTPs for non-email-type users in their organization.\n\n- `Partner Full Admin`: Can generate OTPs for User/Machine Accounts in Customer Orgs.\n\n- `Org User Admin`: Can generate OTPs for User/Machine Accounts within their organization.",
			RunE: func(cmd *cobra.Command, args []string) error {
				req := client.NewRequest(config.CallingBaseURL, "POST", "/identity/organizations/{orgId}/users/{userId}/actions/generateOtp")
				req.PathParam("orgId", orgId)
				req.PathParam("userId", userId)
				resp, statusCode, err := req.Do()
				if err != nil {
					return err
				}
				return output.Print(resp, statusCode)
			},
		}
		cmd.Flags().StringVar(&orgId, "org-id", "", "The Webex Identity-assigned organization identifier for a user's organization.")
		cmd.MarkFlagRequired("org-id")
		cmd.Flags().StringVar(&userId, "user-id", "", "The Common Identity-assigned user identifier for an existing user (`entryUUID`).")
		cmd.MarkFlagRequired("user-id")
		identityOrgCmd.AddCommand(cmd)
	}

}
